<?php
// auth-generated by ModuleConfigHandler
// date: 12/20/2019 15:35:23
define('MOD_SETUPLOAD_ENABLED', true);
define('MOD_SETUPLOAD_TITLE', 'setupload Mojavi Module');
define('MOD_SETUPLOAD_VERSION', 1.0);
define('MOD_SETUPLOAD_NAME', 'setupload');
define('MOD_SETUPLOAD_AUTHOR', 'dhb');
define('MOD_SETUPLOAD_HOMEPAGE', null);
define('MOD_SETUPLOAD_UPDATE_URL', null);
define('MOD_SETUPLOAD_DESCRIPTION', 'setupload Mojavi Module');
?>