<?php
// auth-generated by ModuleConfigHandler
// date: 12/20/2019 17:11:36
define('MOD_REPORT_ENABLED', true);
define('MOD_REPORT_TITLE', 'report Mojavi Module');
define('MOD_REPORT_VERSION', 1.0);
define('MOD_REPORT_NAME', 'report');
define('MOD_REPORT_AUTHOR', 'fly');
define('MOD_REPORT_HOMEPAGE', null);
define('MOD_REPORT_UPDATE_URL', null);
define('MOD_REPORT_DESCRIPTION', 'report Mojavi Module');
?>