<?php
// auth-generated by ModuleConfigHandler
// date: 12/20/2019 16:05:10
define('MOD_PAYMENT_ENABLED', true);
define('MOD_PAYMENT_TITLE', 'payment Mojavi Module');
define('MOD_PAYMENT_VERSION', 1.0);
define('MOD_PAYMENT_NAME', 'payment');
define('MOD_PAYMENT_AUTHOR', 'st');
define('MOD_PAYMENT_HOMEPAGE', null);
define('MOD_PAYMENT_UPDATE_URL', null);
define('MOD_PAYMENT_DESCRIPTION', 'payment Mojavi Module');
?>