<?php
// auth-generated by ModuleConfigHandler
// date: 12/20/2019 16:10:46
define('MOD_SEARCH_CONFIGURATION_ENABLED', true);
define('MOD_SEARCH_CONFIGURATION_TITLE', 'search_configuration Mojavi Module');
define('MOD_SEARCH_CONFIGURATION_VERSION', 1.0);
define('MOD_SEARCH_CONFIGURATION_NAME', 'search_configuration');
define('MOD_SEARCH_CONFIGURATION_AUTHOR', 'dhb');
define('MOD_SEARCH_CONFIGURATION_HOMEPAGE', null);
define('MOD_SEARCH_CONFIGURATION_UPDATE_URL', null);
define('MOD_SEARCH_CONFIGURATION_DESCRIPTION', 'search_configuration Mojavi Module');
?>