<?php
// auth-generated by ModuleConfigHandler
// date: 12/20/2019 15:42:22
define('MOD_CLIENT_ENABLED', true);
define('MOD_CLIENT_TITLE', 'client Mojavi Module');
define('MOD_CLIENT_VERSION', 1.0);
define('MOD_CLIENT_NAME', 'client');
define('MOD_CLIENT_AUTHOR', 'dhb');
define('MOD_CLIENT_HOMEPAGE', null);
define('MOD_CLIENT_UPDATE_URL', null);
define('MOD_CLIENT_DESCRIPTION', 'client Mojavi Module');
?>