<?php
// auth-generated by ModuleConfigHandler
// date: 12/20/2019 17:39:22
define('MOD_APP_ENABLED', true);
define('MOD_APP_TITLE', 'app Mojavi Module');
define('MOD_APP_VERSION', 1.0);
define('MOD_APP_NAME', 'app');
define('MOD_APP_AUTHOR', 'dhb');
define('MOD_APP_HOMEPAGE', null);
define('MOD_APP_UPDATE_URL', null);
define('MOD_APP_DESCRIPTION', 'app Mojavi Module');
?>