<?php
// auth-generated by ModuleConfigHandler
// date: 12/24/2019 12:17:37
define('MOD_GUIDE_ENABLED', true);
define('MOD_GUIDE_TITLE', 'guide Mojavi Module');
define('MOD_GUIDE_VERSION', 1.0);
define('MOD_GUIDE_NAME', 'guide');
define('MOD_GUIDE_AUTHOR', 'dhb');
define('MOD_GUIDE_HOMEPAGE', null);
define('MOD_GUIDE_UPDATE_URL', null);
define('MOD_GUIDE_DESCRIPTION', 'guide Mojavi Module');
?>