<?php
// auth-generated by ModuleConfigHandler
// date: 12/20/2019 16:57:34
define('MOD_MCH_ENABLED', true);
define('MOD_MCH_TITLE', 'mch Mojavi Module');
define('MOD_MCH_VERSION', 1.0);
define('MOD_MCH_NAME', 'mch');
define('MOD_MCH_AUTHOR', 'st');
define('MOD_MCH_HOMEPAGE', null);
define('MOD_MCH_UPDATE_URL', null);
define('MOD_MCH_DESCRIPTION', 'mch Mojavi Module');
?>