<?php
// auth-generated by ModuleConfigHandler
// date: 12/20/2019 16:57:39
define('MOD_INTEGRAL_ENABLED', true);
define('MOD_INTEGRAL_TITLE', 'integral Mojavi Module');
define('MOD_INTEGRAL_VERSION', 1.0);
define('MOD_INTEGRAL_NAME', 'integral');
define('MOD_INTEGRAL_AUTHOR', 'dhb');
define('MOD_INTEGRAL_HOMEPAGE', null);
define('MOD_INTEGRAL_UPDATE_URL', null);
define('MOD_INTEGRAL_DESCRIPTION', 'integral Mojavi Module');
?>