<?php
// auth-generated by ModuleConfigHandler
// date: 12/20/2019 15:41:14
define('MOD_ORDERSLIST_ENABLED', true);
define('MOD_ORDERSLIST_TITLE', 'orderslist Mojavi Module');
define('MOD_ORDERSLIST_VERSION', 1.0);
define('MOD_ORDERSLIST_NAME', 'orderslist');
define('MOD_ORDERSLIST_AUTHOR', 'fly');
define('MOD_ORDERSLIST_HOMEPAGE', null);
define('MOD_ORDERSLIST_UPDATE_URL', null);
define('MOD_ORDERSLIST_DESCRIPTION', 'orderslist Mojavi Module');
?>