<?php
// auth-generated by ModuleConfigHandler
// date: 12/27/2019 15:24:05
define('MOD_EDITION_ENABLED', true);
define('MOD_EDITION_TITLE', 'edition Mojavi Module');
define('MOD_EDITION_VERSION', 1.0);
define('MOD_EDITION_NAME', 'edition');
define('MOD_EDITION_AUTHOR', 'dhb');
define('MOD_EDITION_HOMEPAGE', null);
define('MOD_EDITION_UPDATE_URL', null);
define('MOD_EDITION_DESCRIPTION', 'edition Mojavi Module');
?>