<?php
// auth-generated by ModuleConfigHandler
// date: 12/30/2019 10:42:00
define('MOD_FINANCE_ENABLED', true);
define('MOD_FINANCE_TITLE', 'finance Mojavi Module');
define('MOD_FINANCE_VERSION', 1.0);
define('MOD_FINANCE_NAME', 'finance');
define('MOD_FINANCE_AUTHOR', 'fly');
define('MOD_FINANCE_HOMEPAGE', null);
define('MOD_FINANCE_UPDATE_URL', null);
define('MOD_FINANCE_DESCRIPTION', 'finance Mojavi Module');
?>