<?php
// auth-generated by ModuleConfigHandler
// date: 12/20/2019 16:57:33
define('MOD_SUBTRACTION_ENABLED', true);
define('MOD_SUBTRACTION_TITLE', 'subtraction Mojavi Module');
define('MOD_SUBTRACTION_VERSION', 1.0);
define('MOD_SUBTRACTION_NAME', 'subtraction');
define('MOD_SUBTRACTION_AUTHOR', 'dhb');
define('MOD_SUBTRACTION_HOMEPAGE', null);
define('MOD_SUBTRACTION_UPDATE_URL', null);
define('MOD_SUBTRACTION_DESCRIPTION', 'subtraction Mojavi Module');
?>