<?php
// auth-generated by ModuleConfigHandler
// date: 12/20/2019 16:57:37
define('MOD_DISTRIBUTION_ENABLED', true);
define('MOD_DISTRIBUTION_TITLE', 'distribution Mojavi Module');
define('MOD_DISTRIBUTION_VERSION', 1.0);
define('MOD_DISTRIBUTION_NAME', 'distribution');
define('MOD_DISTRIBUTION_AUTHOR', 'dhb');
define('MOD_DISTRIBUTION_HOMEPAGE', null);
define('MOD_DISTRIBUTION_UPDATE_URL', null);
define('MOD_DISTRIBUTION_DESCRIPTION', 'distribution Mojavi Module');
?>