<?php
// auth-generated by ModuleConfigHandler
// date: 12/30/2019 19:34:24
define('MOD_INVOICE_ENABLED', true);
define('MOD_INVOICE_TITLE', 'invoice Mojavi Module');
define('MOD_INVOICE_VERSION', 1.0);
define('MOD_INVOICE_NAME', 'invoice');
define('MOD_INVOICE_AUTHOR', 'fly');
define('MOD_INVOICE_HOMEPAGE', null);
define('MOD_INVOICE_UPDATE_URL', null);
define('MOD_INVOICE_DESCRIPTION', 'invoice Mojavi Module');
?>