<?php
// auth-generated by ModuleConfigHandler
// date: 12/20/2019 15:35:33
define('MOD_DATA_DICTIONARY_ENABLED', true);
define('MOD_DATA_DICTIONARY_TITLE', 'data_dictionary Mojavi Module');
define('MOD_DATA_DICTIONARY_VERSION', 1.0);
define('MOD_DATA_DICTIONARY_NAME', 'data_dictionary');
define('MOD_DATA_DICTIONARY_AUTHOR', 'dhb');
define('MOD_DATA_DICTIONARY_HOMEPAGE', null);
define('MOD_DATA_DICTIONARY_UPDATE_URL', null);
define('MOD_DATA_DICTIONARY_DESCRIPTION', 'data_dictionary Mojavi Module');
?>