<?php
// auth-generated by ModuleConfigHandler
// date: 12/30/2019 10:50:23
define('MOD_MESSAGE_ENABLED', true);
define('MOD_MESSAGE_TITLE', 'message Mojavi Module');
define('MOD_MESSAGE_VERSION', 1.0);
define('MOD_MESSAGE_NAME', 'message');
define('MOD_MESSAGE_AUTHOR', 'dhb');
define('MOD_MESSAGE_HOMEPAGE', null);
define('MOD_MESSAGE_UPDATE_URL', null);
define('MOD_MESSAGE_DESCRIPTION', 'message Mojavi Module');
?>