<?php
// auth-generated by ModuleConfigHandler
// date: 12/30/2019 10:50:21
define('MOD_SALE_ENABLED', true);
define('MOD_SALE_TITLE', 'sale Mojavi Module');
define('MOD_SALE_VERSION', 1.0);
define('MOD_SALE_NAME', 'sale');
define('MOD_SALE_AUTHOR', 'dhb');
define('MOD_SALE_HOMEPAGE', null);
define('MOD_SALE_UPDATE_URL', null);
define('MOD_SALE_DESCRIPTION', 'sale Mojavi Module');
?>