<?php
// auth-generated by ModuleConfigHandler
// date: 12/30/2019 10:41:44
define('MOD_RETURN_ENABLED', true);
define('MOD_RETURN_TITLE', 'return Mojavi Module');
define('MOD_RETURN_VERSION', 1.0);
define('MOD_RETURN_NAME', 'return');
define('MOD_RETURN_AUTHOR', 'dhb');
define('MOD_RETURN_HOMEPAGE', null);
define('MOD_RETURN_UPDATE_URL', null);
define('MOD_RETURN_DESCRIPTION', 'return Mojavi Module');
?>