<?php
// auth-generated by ModuleConfigHandler
// date: 12/20/2019 15:35:25
define('MOD_SYSTEMTELL_ENABLED', true);
define('MOD_SYSTEMTELL_TITLE', 'systemtell Mojavi Module');
define('MOD_SYSTEMTELL_VERSION', 1.0);
define('MOD_SYSTEMTELL_NAME', 'systemtell');
define('MOD_SYSTEMTELL_AUTHOR', 'dhb');
define('MOD_SYSTEMTELL_HOMEPAGE', null);
define('MOD_SYSTEMTELL_UPDATE_URL', null);
define('MOD_SYSTEMTELL_DESCRIPTION', 'systemtell Mojavi Module');
?>