<?php
// auth-generated by ModuleConfigHandler
// date: 12/30/2019 20:17:30
define('MOD_FREIGHT_ENABLED', true);
define('MOD_FREIGHT_TITLE', 'freight Mojavi Module');
define('MOD_FREIGHT_VERSION', 1.0);
define('MOD_FREIGHT_NAME', 'freight');
define('MOD_FREIGHT_AUTHOR', 'dhb');
define('MOD_FREIGHT_HOMEPAGE', null);
define('MOD_FREIGHT_UPDATE_URL', null);
define('MOD_FREIGHT_DESCRIPTION', 'freight Mojavi Module');
?>