<?php
// auth-generated by ModuleConfigHandler
// date: 12/30/2019 10:50:14
define('MOD_GO_GROUP_ENABLED', true);
define('MOD_GO_GROUP_TITLE', 'go_group Mojavi Module');
define('MOD_GO_GROUP_VERSION', 1.0);
define('MOD_GO_GROUP_NAME', 'go_group');
define('MOD_GO_GROUP_AUTHOR', 'dhb');
define('MOD_GO_GROUP_HOMEPAGE', null);
define('MOD_GO_GROUP_UPDATE_URL', null);
define('MOD_GO_GROUP_DESCRIPTION', 'go_group Mojavi Module');
?>