<?php
// auth-generated by ModuleConfigHandler
// date: 12/30/2019 10:50:16
define('MOD_BARGAIN_ENABLED', true);
define('MOD_BARGAIN_TITLE', 'bargain Mojavi Module');
define('MOD_BARGAIN_VERSION', 1.0);
define('MOD_BARGAIN_NAME', 'bargain');
define('MOD_BARGAIN_AUTHOR', 'dhb');
define('MOD_BARGAIN_HOMEPAGE', null);
define('MOD_BARGAIN_UPDATE_URL', null);
define('MOD_BARGAIN_DESCRIPTION', 'bargain Mojavi Module');
?>