<?php
// auth-generated by ModuleConfigHandler
// date: 12/20/2019 16:10:46
define('MOD_SYSTEM_ENABLED', true);
define('MOD_SYSTEM_TITLE', 'system Mojavi Module');
define('MOD_SYSTEM_VERSION', 1.0);
define('MOD_SYSTEM_NAME', 'system');
define('MOD_SYSTEM_AUTHOR', 'fly');
define('MOD_SYSTEM_HOMEPAGE', null);
define('MOD_SYSTEM_UPDATE_URL', null);
define('MOD_SYSTEM_DESCRIPTION', 'system Mojavi Module');
?>