<?php
// auth-generated by ModuleConfigHandler
// date: 12/20/2019 15:35:14
define('MOD_CUSTOMER_ENABLED', true);
define('MOD_CUSTOMER_TITLE', 'Customer Mojavi Module');
define('MOD_CUSTOMER_VERSION', 1.0);
define('MOD_CUSTOMER_NAME', 'Customer');
define('MOD_CUSTOMER_AUTHOR', 'dhb');
define('MOD_CUSTOMER_HOMEPAGE', null);
define('MOD_CUSTOMER_UPDATE_URL', null);
define('MOD_CUSTOMER_DESCRIPTION', 'Customer Mojavi Module');
?>