<?php
// auth-generated by ModuleConfigHandler
// date: 12/30/2019 15:10:43
define('MOD_AUCTION_ENABLED', true);
define('MOD_AUCTION_TITLE', 'auction Mojavi Module');
define('MOD_AUCTION_VERSION', 1.0);
define('MOD_AUCTION_NAME', 'auction');
define('MOD_AUCTION_AUTHOR', 'fly');
define('MOD_AUCTION_HOMEPAGE', null);
define('MOD_AUCTION_UPDATE_URL', null);
define('MOD_AUCTION_DESCRIPTION', 'auction Mojavi Module');
?>