<?php
// auth-generated by ModuleConfigHandler
// date: 12/20/2019 15:35:34
define('MOD_THIRD_ENABLED', true);
define('MOD_THIRD_TITLE', 'third Mojavi Module');
define('MOD_THIRD_VERSION', 1.0);
define('MOD_THIRD_NAME', 'third');
define('MOD_THIRD_AUTHOR', 'fly');
define('MOD_THIRD_HOMEPAGE', null);
define('MOD_THIRD_UPDATE_URL', null);
define('MOD_THIRD_DESCRIPTION', 'third Mojavi Module');
?>