<?php
// auth-generated by ModuleConfigHandler
// date: 12/20/2019 16:57:40
define('MOD_SECONDS_ENABLED', true);
define('MOD_SECONDS_TITLE', 'seconds Mojavi Module');
define('MOD_SECONDS_VERSION', 1.0);
define('MOD_SECONDS_NAME', 'seconds');
define('MOD_SECONDS_AUTHOR', 'lm');
define('MOD_SECONDS_HOMEPAGE', null);
define('MOD_SECONDS_UPDATE_URL', null);
define('MOD_SECONDS_DESCRIPTION', 'seconds Mojavi Module');
?>