<?php
// auth-generated by ModuleConfigHandler
// date: 12/30/2019 10:50:39
define('MOD_TAOBAO_ENABLED', true);
define('MOD_TAOBAO_TITLE', 'taobao Mojavi Module');
define('MOD_TAOBAO_VERSION', 1.0);
define('MOD_TAOBAO_NAME', 'taobao');
define('MOD_TAOBAO_AUTHOR', 'dhb');
define('MOD_TAOBAO_HOMEPAGE', null);
define('MOD_TAOBAO_UPDATE_URL', null);
define('MOD_TAOBAO_DESCRIPTION', 'taobao Mojavi Module');
?>