<?php /* Smarty version 2.6.31, created on 2019-12-20 15:35:33
         compiled from Index.tpl */ ?>
<?php $_smarty_tpl_vars = $this->_tpl_vars;
$this->_smarty_include(array('smarty_include_tpl_file' => "../../include_path/header.tpl", 'smarty_include_vars' => array('sitename' => "公共头部")));
$this->_tpl_vars = $_smarty_tpl_vars;
unset($_smarty_tpl_vars);
 ?><?php echo '<style>td a{    width: 44%;    margin: 2%!important;    float: left;}.wrap {    width: 60px;    height: 30px;    background-color: #ccc;    border-radius: 16px;    position: relative;    transition: 0.3s;    margin-left: 10px;}.circle {    width: 29px;    height: 29px;    background-color: #fff;    border-radius: 50%;    position: absolute;    left: 0px;    transition: 0.3s;    box-shadow: 0px 1px 5px rgba(0, 0, 0, .5);}.circle:hover {    transform: scale(1.2);    box-shadow: 0px 1px 8px rgba(0, 0, 0, .5);}.stopCss:hover {    cursor: not-allowed;}.stopCss {    width: 56px;    height: 20px;    border: 1px solid #e9ecef;    color: #d8dbe8 !important;    font-size: 12px;    border-radius: 2px;    line-height: 20px;    display: inline-block;}</style>'; ?>
</head><body><?php $_smarty_tpl_vars = $this->_tpl_vars;
$this->_smarty_include(array('smarty_include_tpl_file' => "../../include_path/nav.tpl", 'smarty_include_vars' => array('sitename' => "面包屑")));
$this->_tpl_vars = $_smarty_tpl_vars;
unset($_smarty_tpl_vars);
 ?><div class="pd-20 page_absolute">    <div class="text-c">        <form name="form1" action="index.php" method="get">            <input type="hidden" name="module" value="data_dictionary" />            <input type="text" name="code" size='8' value="<?php echo $this->_tpl_vars['code']; ?>
" id="code" placeholder="请输入数据编码" style="width:200px" class="input-text">            <input type="text" name="name" size='8' value="<?php echo $this->_tpl_vars['name']; ?>
" id="name" placeholder="请输入数据名称" style="width:200px" class="input-text">            <input type="text" name="attribute_value" size='8' value="<?php echo $this->_tpl_vars['attribute_value']; ?>
" id="attribute_value" placeholder="请输入所属属性值" style="width:200px" class="input-text">            <input type="button" value="重置" id="btn8" style="border: 1px solid #D5DBE8; color: #6a7076; height: 31px;" class="reset" onclick="empty()" />            <input name="" id="" class="btn btn-success" type="submit" value="查询" >        </form>    </div>    <div class="page_h16"></div>    <div style="clear:both;" class="page_bgcolor">        <a class="btn newBtn radius" href="index.php?module=data_dictionary&action=Add" style="width: 136px;"><img style="margin-right: 2px!important;height: 14px;" src="images/icon1/add.png"/>&nbsp;添加数据字典</a>        <a class="btn newBtn radius" href="index.php?module=data_dictionary&action=List" style="float: right;">数据名称管理</a>    </div>    <div class="page_h16"></div>    <div class="mt-20 table-scroll">        <div class="tab_table">            <table class="table-border tab_content">                <thead>                    <tr class="text-c tab_tr">                        <th>数据编码</th>                        <th>数据名称</th>                        <th>值</th>                        <th>所属属性名称</th>                        <th>是否生效</th>                        <th>添加人</th>                        <th class="tab_time">添加时间</th>                        <th class="tab_editor">操作</th>                    </tr>                </thead>                <tbody>                    <input type="hidden" class="status" name="num" id="num" value='<?php echo $this->_tpl_vars['num']; ?>
'>                    <?php $_from = $this->_tpl_vars['list']; if (!is_array($_from) && !is_object($_from)) { settype($_from, 'array'); }$this->_foreach['f1'] = array('total' => count($_from), 'iteration' => 0);
if ($this->_foreach['f1']['total'] > 0):
    foreach ($_from as $this->_tpl_vars['k'] => $this->_tpl_vars['item']):
        $this->_foreach['f1']['iteration']++;
?>                    <tr class="text-c tab_td">                        <td><?php echo $this->_tpl_vars['item']->code; ?>
</td>                        <td><?php echo $this->_tpl_vars['item']->name; ?>
</td>                        <td><?php echo $this->_tpl_vars['item']->text; ?>
</td>                        <td><?php echo $this->_tpl_vars['item']->s_name; ?>
</td>                        <td style="display: flex;align-items: center;justify-content: center;">                            <div class="formControls col-2" style="width: 60px;">                                <div class="status_box">                                    <input type="hidden" class="status" name="status" id="status_<?php echo $this->_tpl_vars['k']; ?>
" value="<?php echo $this->_tpl_vars['item']->status; ?>
">                                    <div class="wrap" onclick="up(<?php echo $this->_tpl_vars['k']; ?>
,<?php echo $this->_tpl_vars['item']->id; ?>
)" style="margin: 0;<?php if ($this->_tpl_vars['item']->status == 1): ?>background-color:#5eb95e;<?php else: ?>background-color: #ccc;<?php endif; ?>">                                        <div class="circle" id="circle_<?php echo $this->_tpl_vars['k']; ?>
" style="<?php if ($this->_tpl_vars['item']->status == 1): ?>left:30px;<?php else: ?>left:0px;<?php endif; ?>"></div>                                    </div>                                </div>                            </div>                        </td>                        <td><?php echo $this->_tpl_vars['item']->admin_name; ?>
</td>                        <td class="tab_time"><?php echo $this->_tpl_vars['item']->add_date; ?>
</td>                        <td class="tab_editor">                            <div class="tab_block">                                <?php if ($this->_tpl_vars['item']->status_status): ?>                                    <a style="text-decoration:none" class="ml-5" href="index.php?module=data_dictionary&action=Modify&id=<?php echo $this->_tpl_vars['item']->id; ?>
" title="编辑" >                                        <img src="images/icon1/xg.png"/>&nbsp;编辑                                    </a>                                    <a style="text-decoration:none" class="ml-5" href="javascript:void(0);" onclick="confirm('确定要删除此数据吗?',<?php echo $this->_tpl_vars['item']->id; ?>
,'index.php?module=data_dictionary&action=Del&id=','删除')">                                        <img src="images/icon1/del.png"/>&nbsp;删除                                    </a>                                <?php else: ?>                                    <a class="ml-5 stopCss" href="javascript:void(0);" >                                        <img src="images/icon1/xg.png"/>&nbsp;编辑                                    </a>                                    <a class="ml-5 stopCss" href="javascript:void(0);" >                                        <img src="images/icon1/del.png"/>&nbsp;删除                                    </a>                                <?php endif; ?>                            </div>                        </td>                    </tr>                    <?php endforeach; endif; unset($_from); ?>                </tbody>            </table>        </div>    </div>    <div class="tbtab" style="text-align: center;display: flex;justify-content: center;"><?php echo $this->_tpl_vars['pages_show']; ?>
</div></div><?php $_smarty_tpl_vars = $this->_tpl_vars;
$this->_smarty_include(array('smarty_include_tpl_file' => "../../include_path/footer.tpl", 'smarty_include_vars' => array()));
$this->_tpl_vars = $_smarty_tpl_vars;
unset($_smarty_tpl_vars);
 ?><?php echo '<script type="text/javascript">	// 根据框架可视高度,减去现有元素高度,得出表格高度	var Vheight = $(window).height()-56-56-16-36-16-($(\'.tbtab\').text()?70:0)	$(\'.table-scroll\').css(\'height\',Vheight+\'px\')	function empty() {    $("#code").val(\'\');    $("#name").val(\'\');    $("#attribute_value").val(\'\');}// 开启/关闭function up(obj,id){    var res = document.getElementById(\'status_\'+obj).value;    if(res == 0){        $(\'#circle_\'+obj).css(\'left\', \'30px\'),        $(\'#circle_\'+obj).css(\'background-color\', \'#fff\'),        $(\'#circle_\'+obj).parent(".wrap").css(\'background-color\', \'#5eb95e\');        $(\'#status_\'+obj).val(1);    }else{        $(\'#circle_\'+obj).css(\'left\', \'0px\'),        $(\'#circle_\'+obj).css(\'background-color\', \'#fff\'),        $(\'#circle_\'+obj).parent(".wrap").css(\'background-color\', \'#ccc\');        $(\'#status_\'+obj).val(0);    }    $.ajax({        type: "POST",        dataType: "json",        url: \'index.php?module=data_dictionary&action=Index\',        data: {            id:id        },        success: function (data) {            layer.msg(data.status, {time: 2000});            location=location;        }    });}function confirm (content,id,url,content1){    $("body",parent.document).append(`        <div class="maskNew">            <div class="maskNewContent">                <a href="javascript:void(0);" class="closeA" onclick=closeMask1() ><img src="images/icon1/gb.png"/></a>                <div class="maskTitle">提示</div>                <div style="text-align:center;margin-top:30px"><img src="images/icon1/ts.png"></div>                <div style="height: 50px;position: relative;top:20px;font-size: 22px;text-align: center;">                    ${content}                </div>                <div style="text-align:center;margin-top:30px">                    <button class="closeMask" style="margin-right:20px" onclick=closeMask("${id}","${url}","${content1}") >确认</button>                    <button class="closeMask" onclick=closeMask1() >取消</button>                </div>            </div>        </div>    `)}</script>'; ?>
</body></html>