<?php

//小程序界面控制和界面路径
$front = array(
    array(
        'name' => '添加地址',
        'url' => '/pages/address/addAddress',
        'status' => false,
        'parameter' => '',
        'parameter_status' => false
    ),
    array(
        'name' => '地址列表',
        'url' => '/pages/address/receivingAddress',
        'status' => false,
        'parameter' => '',
        'parameter_status' => false
    ),
    array(
        'name' => '搜索订单',
        'url' => '/pagesA/afterSale/afterSale',
        'status' => false,
        'parameter' => '',
        'parameter_status' => false
    ),
    array(
        'name' => '竞拍',
        'url' => '/pages/bidding/bidding',
        'status' => false,
        'parameter' => '',
        'parameter_status' => false
    ),
    array(
        'name' => '竞拍详情',
        'url' => '/pages/bidding/bidding_detailed',
        'status' => false,
        'parameter' => '',
        'parameter_status' => false
    ),
    array(
        'name' => '竞拍记录',
        'url' => '/pages/bidding/bidding_record',
        'status' => false,
        'parameter' => '',
        'parameter_status' => false
    ),
    array(
        'name' => '我的收藏',
        'url' => '/pages/collection/collection',
        'status' => false,
        'parameter' => '',
        'parameter_status' => false,
    ),
    array(
        'name' => '找相似',
        'url' => '/pages/collection/discover',
        'status' => false,
        'parameter' => '',
        'parameter_status' => false,
    ),
    array(
        'name' => '评价',
        'url' => '/pages/evaluate/evaluate',
        'status' => false,
        'parameter' => '',
        'parameter_status' => false,
    ),
    array(
        'name' => '发布成功',
        'url' => '/pages/evaluate/evaluatEnd',
        'status' => false,
        'parameter' => '',
        'parameter_status' => false,
    ),
    array(
        'name' => '发布成功',
        'url' => '/pages/evaluate/evaluat-end',
        'status' => false,
        'parameter' => '',
        'parameter_status' => false,
    ),
    array(
        'name' => '发布评价',
        'url' => '/pages/evaluate/evaluating',
        'status' => false,
        'parameter' => '',
        'parameter_status' => false,
    ),
    array(
        'name' => '运单',
        'url' => '/pages/expressage/expressage',
        'status' => false,
        'parameter' => '',
        'parameter_status' => false,
    ),
    array(
        'name' => '商品列表',
        'url' => '/pages/goods/goods',
        'status' => true,
        'parameter' => 'cid',
        'parameter_status' => true,
    ),
    array(
        'name' => '商品详情',
        'url' => '/pages/goods/goodsDetailed',
        'status' => true,
        'parameter' => 'productId',
        'parameter_status' => true
    ),
    array(
        'name' => '引导图',
        'url' => '/pages/index/index',
        'status' => false,
        'parameter' => '',
        'parameter_status' => false,
    ),
    array(
        'name' => '登录',
        'url' => '/pages/login/login',
        'status' => false,
        'parameter' => '',
        'parameter_status' => false,
    ),
    array(
        'name' => '用户协议',
        'url' => '/pages/login/agreement',
        'status' => false,
        'parameter' => '',
        'parameter_status' => false,
    ),
    array(
        'name' => '注册',
        'url' => '/pages/login/retrievepassword',
        'status' => false,
        'parameter' => '',
        'parameter_status' => false,
    ),
    array(
        'name' => '消息详情',
        'url' => '/pages/message/detailed_mesage',
        'status' => false,
        'parameter' => '',
        'parameter_status' => false,
    ),
    array(
        'name' => '消息详情',
        'url' => '/pages/message/detailedMesage',
        'status' => false,
        'parameter' => '',
        'parameter_status' => false,
    ),
    array(
        'name' => '消息中心',
        'url' => '/pages/message/message',
        'status' => false,
        'parameter' => '',
        'parameter_status' => false,
    ),
    array(
        'name' => '消息服务',
        'url' => '/pages/message/service',
        'status' => false,
        'parameter' => '',
        'parameter_status' => false,
    ),
    array(
        'name' => '消息系统中心',
        'url' => '/pages/message/system_mesage',
        'status' => false,
        'parameter' => '',
        'parameter_status' => false,
    ),
    array(
        'name' => '消息系统中心',
        'url' => '/pages/message/systemMesage',
        'status' => false,
        'parameter' => '',
        'parameter_status' => false,
    ),
    array(
        'name' => '消息中心',
        'url' => '/pages/my/about_me',
        'status' => false,
        'parameter' => '',
        'parameter_status' => false,
    ),
    array(
        'name' => '关于我们',
        'url' => '/pages/my/aboutMe',
        'status' => false,
        'parameter' => '',
        'parameter_status' => false,
    ),
    array(
        'name' => '积分使用说明',
        'url' => '/pages/my/gradeUse',
        'status' => false,
        'parameter' => '',
        'parameter_status' => false,
    ),
    array(
        'name' => '我的优惠券',
        'url' => '/pages/my/mycoupon',
        'status' => false,
        'parameter' => '',
        'parameter_status' => false,
    ),
    array(
        'name' => '我的信息',
        'url' => '/pages/my/myInfo',
        'status' => false,
        'parameter' => '',
        'parameter_status' => false,
    ),
    array(
        'name' => '我的积分',
        'url' => '/pages/my/myScore',
        'status' => false,
        'parameter' => '',
        'parameter_status' => false,
    ),
    array(
        'name' => '我的钱包',
        'url' => '/pages/myWallet/myback',
        'status' => false,
        'parameter' => '',
        'parameter_status' => false,
    ),
    array(
        'name' => '我的钱包',
        'url' => '/pages/myWallet/myWallet',
        'status' => false,
        'parameter' => '',
        'parameter_status' => false,
    ),
    array(
        'name' => '提现申请',
        'url' => '/pages/myWallet/putForward',
        'status' => false,
        'parameter' => '',
        'parameter_status' => false,
    ),
    array(
        'name' => '充值',
        'url' => '/pages/myWallet/recharge',
        'status' => false,
        'parameter' => '',
        'parameter_status' => false,
    ),
    array(
        'name' => '充值成功',
        'url' => '/pages/myWallet/rechargeSuccess',
        'status' => false,
        'parameter' => '',
        'parameter_status' => false,
    ),
    array(
        'name' => '选择商品列表',
        'url' => '/pages/order/batchOrder',
        'status' => false,
        'parameter' => '',
        'parameter_status' => false,
    ),
    array(
        'name' => '我的订单',
        'url' => '/pages/order/myOrder',
        'status' => false,
        'parameter' => '',
        'parameter_status' => false,
    ),
    array(
        'name' => '订单支付',
        'url' => '/pages/order/order',
        'status' => false,
        'parameter' => '',
        'parameter_status' => false,
    ),
    array(
        'name' => '订单搜索',
        'url' => '/pages/order/orderSearch',
        'status' => false,
        'parameter' => '',
        'parameter_status' => false,
    ),
    array(
        'name' => '订单详情',
        'url' => '/pages/pay/orderDetailsr',
        'status' => false,
        'parameter' => '',
        'parameter_status' => false,
    ),
    array(
        'name' => '支付结果',
        'url' => '/pages/pay/payResult',
        'status' => false,
        'parameter' => '',
        'parameter_status' => false,
    ),
    array(
        'name' => '退货',
        'url' => '/pagesA/returnGoods/refund',
        'status' => false,
        'parameter' => '',
        'parameter_status' => false,
    ),
    array(
        'name' => '退货商品',
        'url' => '/pagesA/returnGoods/returnGoods',
        'status' => false,
        'parameter' => '',
        'parameter_status' => false,
    ),
    array(
        'name' => '引导页',
        'url' => '/pages/index/index',
        'status' => false,
        'parameter' => '',
        'parameter_status' => false,
    ),
    array(
        'name' => '码上购',
        'url' => '/pages/scavenging/scavenging',
        'status' => false,
        'parameter' => '',
        'parameter_status' => false,
    ),
    array(
        'name' => '修改手机号码',
        'url' => '/pages/setUp/changePhone',
        'status' => false,
        'parameter' => '',
        'parameter_status' => false,
    ),
    array(
        'name' => '修改登录密码',
        'url' => '/pages/setUp/loginPassword',
        'status' => false,
        'parameter' => '',
        'parameter_status' => false,
    ),
    array(
        'name' => '设置支付密码',
        'url' => '/pages/setUp/payment',
        'status' => false,
        'parameter' => '',
        'parameter_status' => false,
    ),
    array(
        'name' => '修改支付密码',
        'url' => '/pages/setUp/paymentPassword',
        'status' => false,
        'parameter' => '',
        'parameter_status' => false,
    ),
    array(
        'name' => '设置页面',
        'url' => '/pages/setUp/setUp',
        'status' => false,
        'parameter' => '',
        'parameter_status' => false,
    ),
    array(
        'name' => '领券中心',
        'url' => '/pagesA/shop/coupon',
        'status' => false,
        'parameter' => '',
        'parameter_status' => false,
    ),
//    array(
//        'name' => '幸运大抽奖',
//        'url' => '/pagesA/shop/draw',
//        'status' => false,
//        'parameter' => '',
//        'parameter_status' => false,
//    ),
//    array(
//        'name' => '我的奖品',
//        'url' => '/pages/shop/drawMy',
//        'status' => false,
//        'parameter' => '',
//        'parameter_status' => false,
//    ),
//    array(
//        'name' => '抽奖排行榜',
//        'url' => '/pages/shop/drawRank',
//        'status' => false,
//        'parameter' => '',
//        'parameter_status' => false,
//    ),
    array(
        'name' => '邀请有奖',
        'url' => '/pagesA/shop/invite',
        'status' => false,
        'parameter' => '',
        'parameter_status' => false,
    ),
    array(
        'name' => '签到',
        'url' => '/pages/shop/sign',
        'status' => false,
        'parameter' => '',
        'parameter_status' => false,
    ),
    array(
        'name' => '全部分类',
        'url' => '/pages/tabBar/allGoods',
        'status' => false,
        'parameter' => '',
        'parameter_status' => false,
    ),
    array(
        'name' => '首页',
        'url' => '/pages/tabBar/home',
        'status' => true,
        'parameter' => '',
        'parameter_status' => false,
    ),
    array(
        'name' => '个人中心',
        'url' => '/pages/tabBar/my',
        'status' => false,
        'parameter' => '',
        'parameter_status' => false,
    ),
    array(
        'name' => '购物车',
        'url' => '/pages/tabBar/shoppingCart',
        'status' => false,
        'parameter' => '',
        'parameter_status' => false,
    ),
    array(
        'name' => '砍价',
        'url' => '/pagesA/bargain/bargain',
        'status' => false,
        'parameter' => '',
        'parameter_status' => false,
    ),
    array(
        'name' => '砍价中',
        'url' => '/pagesA/bargain/bargainIng',
        'status' => false,
        'parameter' => '',
        'parameter_status' => false,
    ),
    array(
        'name' => '竞拍',
        'url' => '/pagesA/bidding/bidding',
        'status' => false,
        'parameter' => '',
        'parameter_status' => false,
    ),
    array(
        'name' => '竞拍详情',
        'url' => '/pagesA/bidding/bidding_detailed',
        'status' => false,
        'parameter' => '',
        'parameter_status' => false,
    ),
    array(
        'name' => '竞拍详情',
        'url' => '/pagesA/bidding/bidding_detailed_Two',
        'status' => false,
        'parameter' => '',
        'parameter_status' => false,
    ),
    array(
        'name' => '我的竞拍',
        'url' => '/pagesA/bidding/bidding_my',
        'status' => false,
        'parameter' => '',
        'parameter_status' => false,
    ),
    array(
        'name' => '竞拍记录',
        'url' => '/pagesA/bidding/bidding_record',
        'status' => false,
        'parameter' => '',
        'parameter_status' => false,
    ),
    array(
        'name' => '竞拍规则',
        'url' => '/pagesA/bidding/bidding_rule',
        'status' => false,
        'parameter' => '',
        'parameter_status' => false,
    ),
    array(
        'name' => '分销中心',
        'url' => '/pagesA/distribution/distribution_center',
        'status' => false,
        'parameter' => '',
        'parameter_status' => false,
    ),
    array(
        'name' => '佣金明细',
        'url' => '/pagesA/distribution/distribution_flow',
        'status' => false,
        'parameter' => '',
        'parameter_status' => false,
    ),
    array(
        'name' => '佣金提现',
        'url' => '/pagesA/distribution/distribution_form',
        'status' => false,
        'parameter' => '',
        'parameter_status' => false,
    ),
    array(
        'name' => '分销商品',
        'url' => '/pagesA/distribution/distribution_list',
        'status' => false,
        'parameter' => '',
        'parameter_status' => false,
    ),
    array(
        'name' => '分销提现',
        'url' => '/pagesA/distribution/distribution_result',
        'status' => false,
        'parameter' => '',
        'parameter_status' => false,
    ),
    array(
        'name' => '分销规则',
        'url' => '/pagesA/distribution/distribution_rule',
        'status' => false,
        'parameter' => '',
        'parameter_status' => false,
    ),
    array(
        'name' => '分销分享',
        'url' => '/pagesA/distribution/distribution_share',
        'status' => false,
        'parameter' => '',
        'parameter_status' => false,
    ),
    array(
        'name' => '分销团队',
        'url' => '/pagesA/distribution/distribution_team',
        'status' => false,
        'parameter' => '',
        'parameter_status' => false,
    ),
    array(
        'name' => '分销提现失败',
        'url' => '/pagesA/distribution/distribution_tixianFail',
        'status' => false,
        'parameter' => '',
        'parameter_status' => false,
    ),
    array(
        'name' => '提现明细',
        'url' => '/pagesA/distribution/distribution_tocashFlow',
        'status' => false,
        'parameter' => '',
        'parameter_status' => false,
    ),
    array(
        'name' => '模板页面',
        'url' => '/pagesA/distribution/templet',
        'status' => false,
        'parameter' => '',
        'parameter_status' => false,
    ),
    array(
        'name' => '一起拼团',
        'url' => '/pagesA/group/group',
        'status' => false,
        'parameter' => '',
        'parameter_status' => false,
    ),
    array(
        'name' => '拼团结束',
        'url' => '/pagesA/group/group_end',
        'status' => false,
        'parameter' => '',
        'parameter_status' => false,
    ),
    array(
        'name' => '拼团详情',
        'url' => '/pagesA/group/groupDetailed',
        'status' => false,
        'parameter' => '',
        'parameter_status' => false,
    ),
    array(
        'name' => '拼团订单',
        'url' => '/pagesA/group/groupOrder',
        'status' => false,
        'parameter' => '',
        'parameter_status' => false,
    ),
    array(
        'name' => '拼团支付',
        'url' => '/pagesA/group/payfor',
        'status' => false,
        'parameter' => '',
        'parameter_status' => false,
    ),
    array(
        'name' => '库存管理',
        'url' => '/pagesA/myStore/addStock',
        'status' => false,
        'parameter' => '',
        'parameter_status' => false,
    ),
    array(
        'name' => '入驻协议',
        'url' => '/pagesA/myStore/applyAgreement',
        'status' => false,
        'parameter' => '',
        'parameter_status' => false,
    ),
    array(
        'name' => '申请开店',
        'url' => '/pagesA/myStore/applyStore',
        'status' => false,
        'parameter' => '',
        'parameter_status' => false,
    ),
    array(
        'name' => '申请结果',
        'url' => '/pagesA/myStore/applySuc',
        'status' => false,
        'parameter' => '',
        'parameter_status' => false,
    ),
    array(
        'name' => '商品详情',
        'url' => '/pagesA/myStore/goodsDetail',
        'status' => false,
        'parameter' => '',
        'parameter_status' => false,
    ),
    array(
        'name' => '我的提现',
        'url' => '/pagesA/myStore/myCha',
        'status' => false,
        'parameter' => '',
        'parameter_status' => false,
    ),
    array(
        'name' => '我的客户',
        'url' => '/pagesA/myStore/myCli',
        'status' => false,
        'parameter' => '',
        'parameter_status' => false,
    ),
    array(
        'name' => '账户明细',
        'url' => '/pagesA/myStore/myFinance',
        'status' => false,
        'parameter' => '',
        'parameter_status' => false,
    ),
    array(
        'name' => '我的订单',
        'url' => '/pagesA/myStore/myOrder',
        'status' => false,
        'parameter' => '',
        'parameter_status' => false,
    ),
    array(
        'name' => '我的商品',
        'url' => '/pagesA/myStore/myPro',
        'status' => false,
        'parameter' => '',
        'parameter_status' => false,
    ),
    array(
        'name' => '我的店铺',
        'url' => '/pagesA/myStore/myStore',
        'status' => false,
        'parameter' => '',
        'parameter_status' => false,
    ),
    array(
        'name' => '订单详情',
        'url' => '/pagesA/myStore/order',
        'status' => false,
        'parameter' => '',
        'parameter_status' => false,
    ),
    array(
        'name' => '设置属性',
        'url' => '/pagesA/myStore/setAttr',
        'status' => false,
        'parameter' => '',
        'parameter_status' => false,
    ),
    array(
        'name' => '退货审核',
        'url' => '/pagesA/myStore/storeRefund',
        'status' => false,
        'parameter' => '',
        'parameter_status' => false,
    ),
    array(
        'name' => '店铺设置',
        'url' => '/pagesA/myStore/storeSetup',
        'status' => false,
        'parameter' => '',
        'parameter_status' => false,
    ),
    array(
        'name' => '上传商品',
        'url' => '/pagesA/myStore/uploadPro',
        'status' => false,
        'parameter' => '',
        'parameter_status' => false,
    ),
    array(
        'name' => '搜索商品',
        'url' => '/pagesA/search/search',
        'status' => false,
        'parameter' => '',
        'parameter_status' => false,
    ),
    array(
        'name' => '搜索扫描',
        'url' => '/pagesA/search/scan',
        'status' => false,
        'parameter' => '',
        'parameter_status' => false,
    ),
    array(
        'name' => '搜索结果',
        'url' => '/pagesA/search/searchResult',
        'status' => false,
        'parameter' => '',
        'parameter_status' => false,
    ),
    array(
        'name' => '店铺主页',
        'url' => '/pagesA/store/store',
        'status' => false,
        'parameter' => '',
        'parameter_status' => false,
    )
);
?>
