<?php /* Smarty version 2.6.31, created on 2019-12-31 16:24:20
         compiled from Modify.tpl */ ?>
<?php $_smarty_tpl_vars = $this->_tpl_vars;
$this->_smarty_include(array('smarty_include_tpl_file' => "../../include_path/header.tpl", 'smarty_include_vars' => array('sitename' => "DIY头部")));
$this->_tpl_vars = $_smarty_tpl_vars;
unset($_smarty_tpl_vars);
 ?><?php $_smarty_tpl_vars = $this->_tpl_vars;
$this->_smarty_include(array('smarty_include_tpl_file' => "../../include_path/software_head.tpl", 'smarty_include_vars' => array('sitename' => "DIY头部")));
$this->_tpl_vars = $_smarty_tpl_vars;
unset($_smarty_tpl_vars);
 ?><body class="body_bgcolor"><?php $_smarty_tpl_vars = $this->_tpl_vars;
$this->_smarty_include(array('smarty_include_tpl_file' => "../../include_path/software_img.tpl", 'smarty_include_vars' => array('sitename' => 'DIY_IMG')));
$this->_tpl_vars = $_smarty_tpl_vars;
unset($_smarty_tpl_vars);
 ?><?php $_smarty_tpl_vars = $this->_tpl_vars;
$this->_smarty_include(array('smarty_include_tpl_file' => "../../include_path/nav.tpl", 'smarty_include_vars' => array('sitename' => "面包屑")));
$this->_tpl_vars = $_smarty_tpl_vars;
unset($_smarty_tpl_vars);
 ?><div class="panel-body pd-20">    <form name="form1" id="form1" class="form form-horizontal" method="post" enctype="multipart/form-data">        <input class="link-open-type" name="id" value="<?php echo $this->_tpl_vars['id']; ?>
" type="hidden">        <input class="link-open-type" name="type" id="type" value="<?php echo $this->_tpl_vars['open_type']; ?>
" type="hidden">        <input class="link-open-type" name="y_parameter" id="y_parameter" value="<?php echo $this->_tpl_vars['parameter1']; ?>
" type="hidden">        <input class="link-open-type" name="y_parameter_status" id="y_parameter_status" value="<?php echo $this->_tpl_vars['parameter_status']; ?>
" type="hidden">        <div class="row cl">            <label class="form-label col-4"><span class="c-red">*</span>图片：</label>            <div class="col-sm-6">                <div class="upload-group">                    <div class="input-group">                        <input class="form-control file-input" name="pic_url" value="<?php echo $this->_tpl_vars['image']; ?>
">                        <span class="input-group-btn">                            <a class="btn btn-secondary upload-file" href="javascript:" data-toggle="tooltip"                               data-placement="bottom" title="" data-original-title="上传文件">                                <span class="iconfont icon-cloudupload"></span>                            </a>                        </span>                        <span class="input-group-btn">                            <a class="btn btn-secondary select-file" href="javascript:" data-toggle="tooltip"                               data-placement="bottom" title="" data-original-title="从文件库选择">                                <span class="iconfont icon-viewmodule"></span>                            </a>                        </span>                        <span class="input-group-btn">                            <a class="btn btn-secondary delete-file" href="javascript:" data-toggle="tooltip"                               data-placement="bottom" title="" data-original-title="删除文件">                                <span class="iconfont icon-close"></span>                            </a>                        </span>                    </div>                    <div class="upload-preview text-center upload-preview" style="height: 49px;">                        <span class="upload-preview-tip">750×360</span>                        <img class="upload-preview-img" src="<?php echo $this->_tpl_vars['image']; ?>
">                    </div>                </div>            </div>        </div>        <div class="row cl">            <label class="form-label col-4"><span class="c-red">*</span>跳转类型：</label>            <div class="col-sm-2">                <select name="open_type" class="select" id="select" style="height: 31px;vertical-align: middle;" onClick="show();" >                    <option  value="0">请选择跳转类型</option>                    <?php $_from = $this->_tpl_vars['list']; if (!is_array($_from) && !is_object($_from)) { settype($_from, 'array'); }$this->_foreach['f1'] = array('total' => count($_from), 'iteration' => 0);
if ($this->_foreach['f1']['total'] > 0):
    foreach ($_from as $this->_tpl_vars['item']):
        $this->_foreach['f1']['iteration']++;
?>                        <option  value="<?php echo $this->_tpl_vars['item']->url; ?>
" <?php if ($this->_tpl_vars['open_type'] == $this->_tpl_vars['item']->url): ?>selected<?php endif; ?>><?php echo $this->_tpl_vars['item']->name; ?>
</option>                    <?php endforeach; endif; unset($_from); ?>                </select>            </div>            <text style="color: red;" id="activity_type"></text>        </div>        <div class="row cl" id="parameter1" <?php if (! $this->_tpl_vars['parameter']): ?>style="display: none;"<?php endif; ?>>            <label class="form-label col-4"><span class="c-red">*</span>参数：</label>            <div class="col-sm-6">                <input class="form-control" type="text" name="parameter" id="parameter" value="<?php echo $this->_tpl_vars['parameter']; ?>
" onchange="canshu()">            </div>        </div>        <div class="row cl" >            <label class="form-label col-4"><span class="c-red">*</span>路径：</label>            <div class="col-sm-6">                <input class="form-control" type="text" name="url" id="url" value="<?php echo $this->_tpl_vars['page_url']; ?>
" readonly="readonly" style="background-color: #eeeeee !important">            </div>        </div>    </form>    <div class="page_bort" style="z-index: 999;">        <input type="button" name="Submit" value="保存" class="fo_btn2" onclick="check()">        <input type="button" name="reset" value="取消" class="fo_btn1" onclick="javascript :history.back(-1);">    </div></div><?php $_smarty_tpl_vars = $this->_tpl_vars;
$this->_smarty_include(array('smarty_include_tpl_file' => "../../include_path/software_footer.tpl", 'smarty_include_vars' => array('sitename' => "DIY底部")));
$this->_tpl_vars = $_smarty_tpl_vars;
unset($_smarty_tpl_vars);
 ?><?php echo '    <script>        var url = $(\'#type\').val();        var parameter = $(\'#y_parameter\').val();        var parameter_status = $(\'#y_parameter_status\').val();        function show() {            var obj = $(\'#select option:selected\').val(); // 跳转类型            if(obj != 0){                $.ajax({                    cache: true,                    type: "GET",                    dataType: "json",                    url: \'index.php?module=banner&action=Add&m=open_type&obj=\'+obj,                    data: $(\'#form1\').serialize(),// 你的formid                    async: true,                    success: function (data) {                        var canshu = document.getElementById("parameter").value;                        var url1 = \'\';                        url = data.url;                        parameter = data.parameter;                        parameter_status = data.parameter_status;                        if(parameter_status){                            if(canshu != \'\'){                                url1 = data.url + \'?\' + data.parameter + \'=\' + canshu;                            }else{                                url1 = data.url + \'?\' + data.parameter + \'=\';                            }                            document.getElementById(\'parameter1\').style.display = ""; // 参数显示                        }else{                            url1 = data.url;                            document.getElementById(\'parameter1\').style.display = "none"; // 参数隐藏                        }                        $("#url").val(url1)                    }                });            }else{                $("#url").val(\'\')            }        }        function canshu() {            var canshu = document.getElementById("parameter").value;            var url2 = url + \'?\' + parameter + \'=\' + canshu;            $("#url").val(url2)        }        function check() {            $.ajax({                cache: true,                type: "POST",                dataType: "json",                url: \'index.php?module=banner&action=Modify\',                data: $(\'#form1\').serialize(), // 你的formid                async: true,                success: function (data) {                    layer.msg(data.status, {time: 2000});                    if (data.suc) {                        location.href = \'index.php?module=banner\';                    }                }            });        }    </script>'; ?>
</body></html>