delete from lkt_product_img ;
delete from lkt_product_list ;
delete from lkt_product_class ;
delete from lkt_product_config;
delete from lkt_brand_class;
delete from lkt_order;
delete from lkt_record;
delete from lkt_user;
delete from lkt_mch;
delete from lkt_stock;
delete from lkt_coupon;
delete from lkt_freight;
delete from lkt_return_goods;
delete from lkt_comments;
delete from lkt_subtraction;
delete from lkt_order_details;
delete from lkt_mch_browse;
delete from lkt_order_data;
delete from lkt_sign_record;
delete from lkt_sign_config;
delete from lkt_group_open;
delete from lkt_group_config;
delete from lkt_group_product;
delete from lkt_auction_record;
delete from lkt_auction_config;
delete from lkt_auction_promise;
delete from lkt_auction_product;
delete from lkt_bargain_order;
delete from lkt_bargain_goods;
delete from lkt_bargain_record;
delete from lkt_bargain_config;
delete from lkt_coupon_config;
delete from lkt_coupon_activity;
delete from lkt_subtraction_record;
delete from lkt_subtraction_config;
delete from lkt_mch_store;
delete from lkt_mch_config;
delete from lkt_mch_visit_log;
delete from lkt_mch_common_cat;
delete from lkt_mch_account_log;


delete from lkt_distribution_config;
delete from lkt_distribution_grade;
delete from lkt_distribution_record;
delete from lkt_distribution_withdraw;
delete from lkt_user_distribution;
delete from lkt_integral_class;
delete from lkt_integral_config;
delete from lkt_integral_goods;
delete from lkt_printing;
delete from lkt_taobao;
delete from lkt_template;
delete from lkt_mch_template;
